name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Checkout private test cases
      uses: actions/checkout@v3
      with:
        repository: JustTheCoolest/TestCases-VIT-Timetable-to-Calendar
        token: ${{ secrets.TEST_CASES_REPO_TOKEN }}
        path: private_test_cases

    - uses: actions/setup-python@v3

    - run: python3 -m venv .venv && source .venv/bin/activate

    - run:  pip install -r requirements_for_backend_alone.txt

    - name: Test with unittest
      env:
        TEST_CASES_DIR: private_test_cases/TestCases
      run: python testing.py 2>&1 | tee test_results.txt

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test_results.txt
